@echo off
title 🌾 Krishi MCQ Pro Server Dashboard 🌾
cd /d "%~dp0"
cls

echo ==============================================================
echo           🌾 Krishi MCQ Pro PWA Server Console 🌾
==============================================================
echo.

:: 1. Validate Node.js Environment
echo [1/2] Checking Node.js Environment...
where node >nul 2>nul
if %ERRORLEVEL% equ 0 goto node_ok

:: Try default path fallback
set "PATH=C:\Program Files\nodejs;%PATH%"
where node >nul 2>nul
if %ERRORLEVEL% equ 0 goto node_ok

echo [ERROR] Node.js is not installed or not in PATH!
echo Please install Node.js from https://nodejs.org/ to run the local server.
goto error_exit

:node_ok
echo  - Node.js Version: 
node --version

:: 2. Start dynamic Node.js static server in background (Offline-safe, replaces Python)
echo.
echo [2/2] Resolving Local IP and starting server...
start /min "" node server.js

:: Allow a short delay for server initialization
timeout /t 2 /nobreak >nul

:: Read local IP from ip.json generated by Node.js
set LOCAL_IP=127.0.0.1
if exist ip.json (
    for /f "tokens=2 delims=:,}" %%A in ('findstr "ip" ip.json') do (
        set raw_ip=%%A
    )
)
if not "%raw_ip%"=="" (
    :: Strip quotes from raw parsed IP
    set LOCAL_IP=%raw_ip:"=%
    set LOCAL_IP=%LOCAL_IP: =%
)

echo.
echo ==============================================================
echo   PC WEB APP ACCESS URL:
echo   👉 http://localhost:8080/index.html
echo.
echo   MOBILE DEVICE ACCESS URL (Connect to same WiFi/Hotspot):
echo   👉 http://%LOCAL_IP%:8080/index.html
echo.
echo   [PWA Info] Service Worker Caching is active.
echo   Mobile updates will auto-reload when you save PC edits!
echo ==============================================================
echo.
echo   Instructions for Mobile Setup:
echo   1. Make sure your PC is connected to your phone's Hotspot.
echo   2. Open the Mobile Access URL on your phone's browser.
echo   3. Press "Add to Home Screen" to install it as an App!
echo.
echo ==============================================================
echo.
echo   Instructions:
echo   - Press [Enter] to launch the app in your PC browser.
echo   - Keep this console window open to serve your mobile device!
echo ==============================================================
pause >nul
start "" "http://localhost:8080/index.html"
exit /b 0

:error_exit
echo.
echo [PROCESS FAILED] Server launch terminated due to an error.
pause
exit /b 1
